exp_path: # Path to the directory
ins_num: 25
time_limit: 60
time_gap: 15
succ_only: false

figure_width: 10
figure_height: 10
set_title: true
set_legend: true
marker_size: 20
line_width: 4.0
marker_width: 4.0
text_size: 32
alpha: 1.0

set_shift: 0.1
plot_ci: false
plot_std: false
y_grid: true
x_grid: false

maps:
  - name: "random-32-32-20"
    label: Random
    scens:
      - random
    num_of_agents:
      - 200
      - 250
      - 300
      - 350
      - 400

  - name: "maze-32-32-2"
    label: Maze
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "room-32-32-4"
    label: Room
    scens:
      - random
    num_of_agents:
      - 100
      - 150
      - 200
      - 250
      - 300

  - name: "warehouse-10-20-10-2-1"
    label: Warehouse(M)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "warehouse-20-40-10-2-1"
    label: Warehouse(L)
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

  - name: "den520d"
    label: Game
    scens:
      - random
    num_of_agents:
      - 200
      - 400
      - 600
      - 800
      - 1000

solvers:
  - name: "PP-OPT-LH"
    label: "PP*"
    marker: "P"
    color: "violet"
    markerfacecolor: "violet"
    zorder: 0

  - name: "PP-LH"
    label: "PP"
    marker: "P"
    color: "purple"
    zorder: 1

  - name: "PBS-OPT"
    label: "PBS*"
    marker: "o"
    color: "navy"
    markerfacecolor: "navy"
    zorder: 2

  - name: "PBS"
    label: "PBS"
    marker: "o"
    color: "deepskyblue"
    zorder: 3

  - name: "PBS-greedy"
    label: "GPBS"
    color: "orange"
    marker: "d"
    zorder: 4

  - name: "PBS2-PE-TR-IC-RR0"
    label: "GPBS(PE,TR,IC,SR)"
    color: "red"
    marker: "^"
    zorder: 6